import 'package:flutter/material.dart';

// Veri yapısını yönetmek için bir sınıf oluşturdum. 
// Bu sayede her motor için ayrı ayrı değişken tanımlamak yerine, 
// hepsini tek bir çatı altında toplayabiliyorum. Bu yöntem kodun daha düzenli olmasını sağlıyor.
class Motosiklet {
  final String isim;
  final String aciklama;
  final String resimUrl;
  final String ozellikler; // Temel beygir/hacim/silindir bilgisi
  
  // Ödevde detaylı bilgi istendiği için teknik verileri tek tek tanımladım.
  final String mensei;
  final String hizlanma;
  final String frenMarkasi;
  final String topSpeed;
  final String yakitTuketimi;
  final String depoHacmi;
  final String lastikEbatlari;
  final String kullaniciGorusleri;
  final Color temaRengi; // Her motorun kendi rengi olsun diye bu değişkeni ekledim.
  final String kategori;

  Motosiklet({
    required this.isim,
    required this.aciklama,
    required this.resimUrl,
    required this.ozellikler,
    required this.mensei,
    required this.hizlanma,
    required this.frenMarkasi,
    required this.topSpeed,
    required this.yakitTuketimi,
    required this.depoHacmi,
    required this.lastikEbatlari,
    required this.kullaniciGorusleri,
    required this.temaRengi,
    required this.kategori,
  });
}

// Uygulamada göstereceğimiz tüm motor verilerini bu listede tutuyorum.
// ListView kullanırken bu listeyi döngüye sokup verileri çekmek çok pratik oluyor.
List<Motosiklet> motorlar = [

  // ===================== RACING =====================
  Motosiklet(
    isim: "Yamaha R25",
    kategori: "Racing",
    aciklama: "Hem tasarımı hem de gücüyle başlangıç ve orta seviye için Türkiye'de en çok tercih edilen spor motosikletlerin başında gelir. Agresif grenaj yapısı, çift silindirin verdiği pürüzsüz üst devir gücü ve yüksek devir çeviren motor bloğu ile tam bir Supersport hissiyatı sunar. Özellikle genç sürücüler arasında çok popülerdir.",
    resimUrl: "assets/images/r25.jpg",
    ozellikler: "36 HP, 249cc, Çift Silindir",
    mensei: "Japonya",
    hizlanma: "6.8 sn (0-100 km/s)",
    frenMarkasi: "OEM (Yamaha/Akebono)",
    topSpeed: "175 km/s",
    yakitTuketimi: "3.8 - 4.2 L / 100km",
    depoHacmi: "14 Litre",
    lastikEbatlari: "Ön: 110/70-17 | Arka: 140/70-17",
    kullaniciGorusleri: "«Sınıfının en iyi sesine ve en iyi performans hissine sahip motoru diyebilirim. Ancak yüksek devir çevirmeyi sevdiği için şehir içinde alt devirleri biraz cansız kalabiliyor ve yakıt tüketimi rakiplerine göre bir tık daha fazla. Yine de tasarımı için her şeye değer!»",
    temaRengi: Colors.blue.shade800,
  ),
  Motosiklet(
    isim: "Honda CBR250R",
    kategori: "Racing",
    aciklama: "Güvenilir motor bloğu ve affedici yapısıyla tam bir eğitim ve başlangıç motoru. Tek silindirli yapısı sayesinde alt devirlerde canlı bir tork sunar. Şehir içi kullanımlarda vites değiştirmeden rahatça ilerlemenizi sağlar ve parça fiyatları/yakıt tüketimi konusunda kullanıcısını asla üzmez.",
    resimUrl: "assets/images/cbr250r.jpg",
    ozellikler: "27 HP, 249cc, Tek Silindir",
    mensei: "Japonya",
    hizlanma: "8.5 sn (0-100 km/s)",
    frenMarkasi: "Nissin",
    topSpeed: "148 km/s",
    yakitTuketimi: "3.0 - 3.5 L / 100km",
    depoHacmi: "13 Litre",
    lastikEbatlari: "Ön: 110/70-17 | Arka: 140/70-17",
    kullaniciGorusleri: "«Eğer ilk motorunuz olacaksa düşünmeden alabilirsiniz. Düşüp kalktığınızda grenajları nispeten daha uygundur. Tek silindir olduğu için yüksek devirlerde biraz titreşim yapıyor ama şehir içinde inanılmaz pratik ve çok az yakıyor.»",
    temaRengi: Colors.red.shade700,
  ),
  Motosiklet(
    isim: "Kawasaki Ninja 400",
    kategori: "Racing",
    aciklama: "Eğitimini almış ve biraz daha tecrübe edinmek isteyen, 250cc sınıfının üstünde ancak hala affedici bir sport motor arayanlar için piyasadaki en iyi seçenek. Hafif şasisi ve güçlü motor bloğu ile pist günlerinde bile çok keyifli sürüşler yapmanıza olanak tanır.",
    resimUrl: "assets/images/ninja400.jpg",
    ozellikler: "45 HP, 399cc, Çift Silindir",
    mensei: "Japonya",
    hizlanma: "4.8 sn (0-100 km/s)",
    frenMarkasi: "Nissin",
    topSpeed: "190 km/s",
    yakitTuketimi: "4.2 L / 100km",
    depoHacmi: "14 Litre",
    lastikEbatlari: "Ön: 110/70-17 | Arka: 150/60-17",
    kullaniciGorusleri: "«Ağırlığı 250cc'ler kadar ama gücü 600cc'lere göz kırpıyor. Viraj kabiliyeti muazzam. Sıfırdan başlayan biri için ilk etapta fazla güçlü gelebilir ama sağ elinize hakimseniz uzun yıllar değiştirmeden kullanabilirsiniz.»",
    temaRengi: Colors.green.shade600,
  ),
  Motosiklet(
    isim: "Suzuki GSX250R",
    kategori: "Racing",
    aciklama: "Pürüzsüz çift silindir motoru, konforlu oturuş pozisyonu ve şık tasarımıyla güven veren bir sport tourer. Hızdan ziyade kalite, konfor ve uzun ömürlü bir motosiklet arayan, agresif sürüş sevmeyenler için biçilmiş kaftan.",
    resimUrl: "assets/images/gsx250r.jpg",
    ozellikler: "25 HP, 248cc, Çift Silindir",
    mensei: "Japonya",
    hizlanma: "9.2 sn (0-100 km/s)",
    frenMarkasi: "Nissin",
    topSpeed: "140 km/s",
    yakitTuketimi: "3.2 L / 100km",
    depoHacmi: "15 Litre",
    lastikEbatlari: "Ön: 110/80-17 | Arka: 140/70-17",
    kullaniciGorusleri: "«Motor adeta yağ gibi akıyor, titreşim sıfır denecek kadar az. Diğer 250cc çift silindirlere göre gücü düşük olduğu için çok hızlı ivmelenmiyor ama oturuşu o kadar rahat ki saatlerce inmeden sürebilirsiniz. Kalite hissiyatı muazzam.»",
    temaRengi: Colors.indigo.shade600,
  ),
  Motosiklet(
    isim: "Bajaj Pulsar RS200",
    kategori: "Racing",
    aciklama: "Uygun fiyatı, yedek parça bolluğu ve tatminkar performansıyla tam bir bütçe dostu başlangıç motoru. Hem sport tourer görünümü hem de dik oturuş pozisyonu ile yeni başlayanların en çok tercih ettiği fiyat/performans canavarıdır.",
    resimUrl: "assets/images/rs200.jpg",
    ozellikler: "24.5 HP, 199cc, Tek Silindir",
    mensei: "Hindistan",
    hizlanma: "9.5 sn (0-100 km/s)",
    frenMarkasi: "ByBre",
    topSpeed: "148 km/s",
    yakitTuketimi: "3.0 L / 100km",
    depoHacmi: "13 Litre",
    lastikEbatlari: "Ön: 100/80-17 | Arka: 130/70-17",
    kullaniciGorusleri: "«İlk motorumdu ve beni hiç üzmedi. Çok dengeli bir motor, ABS frenleri yeni başlayanlar için hayat kurtarıcı. Parçası o kadar ucuz ki grenajı çizilince dert etmiyorsunuz. Işıklandırması mercekli olduğu için gece sürüşü çok keyifli.»",
    temaRengi: Colors.black,
  ),

  // ===================== NAKED =====================
  Motosiklet(
    isim: "KTM Duke 390",
    kategori: "Naked",
    aciklama: "Şehir içi agresif görünümü ve namıdiğer 'Tork Canavarı' yapısıyla naked sevenler için ideal bir model. Ride-by-wire (elektronik gaz kolu), TFT renkli ekranı ve kaydırmalı debriyajı ile sınıfında en dolu teknolojik özelliklere sahip motorlardan biridir.",
    resimUrl: "assets/images/duke390.jpg",
    ozellikler: "44 HP, 373cc, Tek Silindir",
    mensei: "Avusturya",
    hizlanma: "5.2 sn (0-100 km/s)",
    frenMarkasi: "ByBre",
    topSpeed: "168 km/s",
    yakitTuketimi: "4.0 - 4.5 L / 100km",
    depoHacmi: "13.4 Litre",
    lastikEbatlari: "Ön: 110/70-17 | Arka: 150/60-17",
    kullaniciGorusleri: "«Gaza bastığınız an sizi geriye fırlatan o tork hissi bağımlılık yapıyor. Üzerindeki frenler (ByBre) gerçekten çok güven veriyor. Tek eksi yönü selesinin biraz sert olması; uzun yolda yorabiliyor ama şehir içi için üretilmiş bir Holigan.»",
    temaRengi: Colors.orange.shade800,
  ),
  Motosiklet(
    isim: "CF Moto 250NK",
    kategori: "Naked",
    aciklama: "Tasarımı meşhur Kiska stüdyolarından çıkan, hafifliği ve çevikliği sayesinde ilk motorunu arayanlar için harika bir naked alternatifi. Fiyat bandına göre sunduğu sürüş modları (Eco/Sport) ve renkli ekranı çok cezbedici.",
    resimUrl: "assets/images/nk250.jpg",
    ozellikler: "27 HP, 249cc, Tek Silindir",
    mensei: "Çin",
    hizlanma: "8.0 sn (0-100 km/s)",
    frenMarkasi: "J.Juan (İspanyol)",
    topSpeed: "150 km/s",
    yakitTuketimi: "3.5 L / 100km",
    depoHacmi: "12.5 Litre",
    lastikEbatlari: "Ön: 110/70-17 | Arka: 140/60-17",
    kullaniciGorusleri: "«Çinli algısını yıkan motorlardan biri. J.Juan marka çelik hortumlu frenleri mükemmel tutuyor. Çok dar alanlardan bile bisiklet gibi geçebiliyorsunuz. Sadece arka sele yolcu için biraz rahatsız edici.»",
    temaRengi: Colors.teal.shade700,
  ),
  Motosiklet(
    isim: "Yamaha MT-25",
    kategori: "Naked",
    aciklama: "R25'in naked versiyonu olan MT-25, aynı güçlü çift silindir motoru daha dik ve rahat bir oturuş pozisyonuyla sunar. Şehir içi manevra kabiliyeti yüksek, agresif LED ön farı ile dikkat çeken bir street fighter karakterindedir.",
    resimUrl: "assets/images/mt25.jpg",
    ozellikler: "36 HP, 249cc, Çift Silindir",
    mensei: "Japonya",
    hizlanma: "7.0 sn (0-100 km/s)",
    frenMarkasi: "OEM (Yamaha/Akebono)",
    topSpeed: "170 km/s",
    yakitTuketimi: "3.8 - 4.2 L / 100km",
    depoHacmi: "14 Litre",
    lastikEbatlari: "Ön: 110/70-17 | Arka: 140/70-17",
    kullaniciGorusleri: "«R25'in motorunu daha rahat bir pozisyonda sürmek isteyenler için birebir. Şehir içinde çevik ve eğlenceli.»",
    temaRengi: Colors.blue.shade800,
  ),

  // ===================== ENDURO =====================
  Motosiklet(
    isim: "Honda CRF250L",
    kategori: "Enduro",
    aciklama: "Hem asfalt hem de toprak yolda eşit derecede yetenekli olan CRF250L, dual-sport kategorisinin en güvenilir temsilcisidir. Uzun süspansiyon yolu, hafif gövdesi ve Honda'nın efsanevi dayanıklılığı ile macera tutkunlarının vazgeçilmezi.",
    resimUrl: "assets/images/crf250l.jpg",
    ozellikler: "24.4 HP, 250cc, Tek Silindir",
    mensei: "Japonya",
    hizlanma: "9.0 sn (0-100 km/s)",
    frenMarkasi: "Nissin",
    topSpeed: "130 km/s",
    yakitTuketimi: "3.0 L / 100km",
    depoHacmi: "7.8 Litre",
    lastikEbatlari: "Ön: 3.00-21 | Arka: 120/80-18",
    kullaniciGorusleri: "«Orman yollarında, toprak patikalarda bile güven veriyor. Bakım maliyeti çok düşük, Honda güvenilirliği tartışılmaz.»",
    temaRengi: Colors.red.shade600,
  ),
  Motosiklet(
    isim: "Kawasaki KLX250",
    kategori: "Enduro",
    aciklama: "Hafif yapısı ve güçlü tek silindir motoruyla off-road tutkunu yeni başlayanlar için ideal bir enduro motosiklet. Elektrik marşı, düşük sele yüksekliği ve yumuşak güç dağılımı ile her türlü arazide kolayca kontrol edilebilir.",
    resimUrl: "assets/images/KLX250.jpg",
    ozellikler: "22 HP, 249cc, Tek Silindir",
    mensei: "Japonya",
    hizlanma: "10.0 sn (0-100 km/s)",
    frenMarkasi: "OEM Kawasaki",
    topSpeed: "125 km/s",
    yakitTuketimi: "3.2 L / 100km",
    depoHacmi: "7.7 Litre",
    lastikEbatlari: "Ön: 3.00-21 | Arka: 4.60-18",
    kullaniciGorusleri: "«Çamurda, kumda, taşlık yolda hiç takılmadan gidiyor. Hafifliği sayesinde düşse bile kaldırması çok kolay.»",
    temaRengi: Colors.green.shade800,
  ),
  Motosiklet(
    isim: "Suzuki V-Strom 250",
    kategori: "Enduro",
    aciklama: "Adventure touring segmentinin giriş modeli olan V-Strom 250, uzun yol konforu ile hafif arazi kabiliyetini birleştirir. Rüzgar siperi, el korumaları ve geniş selesi ile uzun mesafe sürüşlerinde konfor sunar.",
    resimUrl: "assets/images/v-storm250.jpg",
    ozellikler: "24.7 HP, 248cc, Çift Silindir",
    mensei: "Japonya",
    hizlanma: "11.0 sn (0-100 km/s)",
    frenMarkasi: "Nissin",
    topSpeed: "135 km/s",
    yakitTuketimi: "3.0 L / 100km",
    depoHacmi: "17.3 Litre",
    lastikEbatlari: "Ön: 110/80-17 | Arka: 140/70-17",
    kullaniciGorusleri: "«17 litrelik deposuyla menzil canavarı. Uzun yolda saatlerce sürebiliyorsunuz, oturuşu çok rahat.»",
    temaRengi: Colors.amber.shade700,
  ),

  // ===================== CROSS =====================
  Motosiklet(
    isim: "KTM 250 SX-F",
    kategori: "Cross",
    aciklama: "Motokros pistlerinin mutlak hakimi olan 250 SX-F, yarış DNA'sı ile üretilmiş bir rekabet makinesidir. Chromoly çelik şasisi, WP XACT süspansiyonları ve Brembo frenleri ile profesyonel yarışçıların da tercihi olan bir modeldir.",
    resimUrl: "assets/images/250sxf.jpg",
    ozellikler: "47 HP, 250cc, Tek Silindir",
    mensei: "Avusturya",
    hizlanma: "4.5 sn (0-100 km/s)",
    frenMarkasi: "Brembo",
    topSpeed: "115 km/s",
    yakitTuketimi: "5.0 L / 100km",
    depoHacmi: "7.0 Litre",
    lastikEbatlari: "Ön: 80/100-21 | Arka: 110/90-19",
    kullaniciGorusleri: "«Pistte uçuyor, süspansiyonları her darbeyi yere yapışık kalarak emiyor. Gerçek bir yarış makinesi.»",
    temaRengi: Colors.orange.shade700,
  ),
  Motosiklet(
    isim: "Honda CRF250R",
    kategori: "Cross",
    aciklama: "Honda'nın motokros pistleri için geliştirdiği yarış odaklı model. Yüksek devirli DOHC motoru, Showa süspansiyonları ve ultra hafif şasisiyle hem amatör hem profesyonel yarışçılara hitap eder. Pist dışında kullanıma uygun değildir.",
    resimUrl: "assets/images/crf250r.jpg",
    ozellikler: "41 HP, 250cc, Tek Silindir",
    mensei: "Japonya",
    hizlanma: "4.8 sn (0-100 km/s)",
    frenMarkasi: "Nissin",
    topSpeed: "110 km/s",
    yakitTuketimi: "5.5 L / 100km",
    depoHacmi: "6.3 Litre",
    lastikEbatlari: "Ön: 80/100-21 | Arka: 100/90-19",
    kullaniciGorusleri: "«Honda kalitesiyle yapılmış bir motokros silahı. Bakım aralıkları kısa ama performansı tartışılmaz.»",
    temaRengi: Colors.red.shade800,
  ),
  Motosiklet(
    isim: "Yamaha YZ250F",
    kategori: "Cross",
    aciklama: "Yamaha'nın motokros efsanesi YZ250F, sınıfında en yüksek güç çıkışına sahip motorlardan biridir. Bilateral beam alüminyum şasisi ve KYB süspansiyonları ile virajlarda rakiplerine fark atar. Power Tuner uygulamasıyla motor ayarları telefondan yapılabilir.",
    resimUrl: "assets/images/yz250f.jpg",
    ozellikler: "42 HP, 250cc, Tek Silindir",
    mensei: "Japonya",
    hizlanma: "4.7 sn (0-100 km/s)",
    frenMarkasi: "Nissin",
    topSpeed: "112 km/s",
    yakitTuketimi: "5.2 L / 100km",
    depoHacmi: "6.2 Litre",
    lastikEbatlari: "Ön: 80/100-21 | Arka: 110/90-19",
    kullaniciGorusleri: "«Power Tuner uygulamasıyla motor haritasını pistin durumuna göre ayarlayabiliyorsunuz. Teknoloji harikası.»",
    temaRengi: Colors.blue.shade700,
  ),

  // ===================== CHOPPER =====================
  Motosiklet(
    isim: "Honda Rebel 500",
    kategori: "Chopper",
    aciklama: "Modern cruiser segmentinin en popüler temsilcisi olan Rebel 500, düşük sele yüksekliği ve hafif yapısıyla yeni başlayanlar için bile erişilebilir bir chopper deneyimi sunar. Çift silindir motoru yumuşak ve lineer bir güç dağılımı sağlar.",
    resimUrl: "assets/images/rebel500.jpg",
    ozellikler: "46 HP, 471cc, Çift Silindir",
    mensei: "Japonya",
    hizlanma: "6.5 sn (0-100 km/s)",
    frenMarkasi: "Nissin",
    topSpeed: "165 km/s",
    yakitTuketimi: "3.6 L / 100km",
    depoHacmi: "11.2 Litre",
    lastikEbatlari: "Ön: 130/90-16 | Arka: 150/80-16",
    kullaniciGorusleri: "«Cruiser dünyasına giriş için mükemmel. Sele yüksekliği o kadar düşük ki kısa boylular bile rahatlıkla ayak basıyor.»",
    temaRengi: Colors.grey.shade800,
  ),
  Motosiklet(
    isim: "Regal Raptor Pilder 250",
    kategori: "Chopper",
    aciklama: "Klasik Amerikan chopper çizgilerini modern mühendislikle buluşturan Pilder 250, gösterişli krom detayları ve alçak sele yapısıyla dikkat çeker. V-Twin benzeri güçlü sesi ve geniş arka lastiğiyle gerçek bir cruiser deneyimi sunan, fiyat/performans odaklı bir modeldir.",
    resimUrl: "assets/images/pilder250.jpg",
    ozellikler: "18 HP, 250cc, Tek Silindir",
    mensei: "Çin",
    hizlanma: "13.0 sn (0-100 km/s)",
    frenMarkasi: "OEM Regal Raptor",
    topSpeed: "115 km/s",
    yakitTuketimi: "3.5 L / 100km",
    depoHacmi: "14 Litre",
    lastikEbatlari: "Ön: 90/90-17 | Arka: 130/90-15",
    kullaniciGorusleri: "«Görünümü fiyatının çok üzerinde. Krom detayları ve alçak duruşuyla herkesi etkiledi. Uzun yolda biraz sert ama şehir içi ve gezinti için mükemmel.»",
    temaRengi: Colors.blueGrey.shade800,
  ),
  Motosiklet(
    isim: "Suzuki Intruder 150",
    kategori: "Chopper",
    aciklama: "Küçük motorlu cruiser segmentinin cesur temsilcisi olan Intruder 150, şehir içi kullanım için tasarlanmış kompakt bir chopper'dır. Düşük yakıt tüketimi ve kolay kullanımıyla hem yeni başlayanlar hem de günlük ulaşım arayanlar için uygundur.",
    resimUrl: "assets/images/intruder150.jpg",
    ozellikler: "14.8 HP, 155cc, Tek Silindir",
    mensei: "Hindistan",
    hizlanma: "14.0 sn (0-100 km/s)",
    frenMarkasi: "OEM Suzuki",
    topSpeed: "110 km/s",
    yakitTuketimi: "2.2 L / 100km",
    depoHacmi: "11 Litre",
    lastikEbatlari: "Ön: 90/90-17 | Arka: 130/90-15",
    kullaniciGorusleri: "«Şehir içinde yakıt cimrisi, görünümü fiyatının çok üzerinde duruyor. İlk motor olarak gayet yeterli.»",
    temaRengi: const Color(0xFFC9A96E), // Şampanya rengi
  ),
];
